import 'product.dart';

final List<Product> dummyProducts = [
  // ==================== ELECTRONICS ====================
  Product(
    id: 'p1',
    name: 'WH-1000XM5 Wireless Noise-Cancelling Headphones',
    brand: 'Sony',
    category: 'Electronics',
    description: 'Industry-leading noise cancellation with two processors and 8 microphones. Up to 30-hour battery life with quick charging. Ultra-comfortable lightweight design.',
    price: 349.99,
    oldPrice: 399.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80',
    ],
    rating: 4.8,
    reviewCount: 1420,
    availableStock: 45,
    isFeatured: true,
  ),
  Product(
    id: 'p2',
    name: 'SoundLink Flex Portable Bluetooth Speaker',
    brand: 'Bose',
    category: 'Electronics',
    description: 'State-of-the-art design with astonishing crisp sound and deep bass. Waterproof and dustproof (IP67) with up to 12 hours playtime per charge.',
    price: 149.00,
    oldPrice: 179.00,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80',
    rating: 4.7,
    reviewCount: 890,
    availableStock: 60,
    isFeatured: true,
  ),
  Product(
    id: 'p3',
    name: 'AirPods Pro 2nd Generation with MagSafe Case',
    brand: 'Apple',
    category: 'Electronics',
    description: 'Up to 2x more Active Noise Cancellation. Adaptive Audio dynamically tailors noise control to your environment. Personalized Spatial Audio with dynamic head tracking.',
    price: 249.00,
    image: 'https://images.unsplash.com/photo-1572569533902-3e0e9328bcb2?w=600&q=80',
    rating: 4.9,
    reviewCount: 3120,
    availableStock: 80,
    isFeatured: true,
  ),
  Product(
    id: 'p4',
    name: 'PowerCore 24000mAh 65W Fast Power Bank',
    brand: 'Anker',
    category: 'Electronics',
    description: 'Massive capacity fast-charging portable power bank. Charge 3 devices simultaneously with 65W high-speed USB-C Power Delivery.',
    price: 59.99,
    oldPrice: 79.99,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80',
    rating: 4.6,
    reviewCount: 540,
    availableStock: 120,
  ),

  // ==================== MOBILES ====================
  Product(
    id: 'p5',
    name: 'iPhone 15 Pro 256GB Natural Titanium',
    brand: 'Apple',
    category: 'Mobiles',
    description: 'Forged in titanium with the ground-breaking A17 Pro chip. Customizable Action button and the most powerful iPhone camera system ever.',
    price: 1099.00,
    oldPrice: 1199.00,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80',
    rating: 4.9,
    reviewCount: 2400,
    availableStock: 25,
    isFeatured: true,
  ),
  Product(
    id: 'p6',
    name: 'Galaxy S24 Ultra 5G AI Smartphone',
    brand: 'Samsung',
    category: 'Mobiles',
    description: 'Meet Galaxy S24 Ultra with Galaxy AI. 200MP camera, Snapdragon 8 Gen 3 for Galaxy, titanium frame, and built-in S Pen.',
    price: 1299.99,
    oldPrice: 1399.99,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80',
    rating: 4.8,
    reviewCount: 1850,
    availableStock: 30,
    isFeatured: true,
  ),
  Product(
    id: 'p7',
    name: 'Pixel 8 Pro with Google Tensor G3',
    brand: 'Google',
    category: 'Mobiles',
    description: 'The all-pro phone engineered by Google. Next-level computational photography, Super Actua display, and all-day intelligent battery.',
    price: 899.00,
    oldPrice: 999.00,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351cb31b?w=600&q=80',
    rating: 4.7,
    reviewCount: 940,
    availableStock: 40,
  ),
  Product(
    id: 'p8',
    name: 'Armor Tough MagSafe Protective Case',
    brand: 'Spigen',
    category: 'Mobiles',
    description: 'Military-grade drop protection with air cushion technology and integrated magnetic ring for seamless wireless charging accessories.',
    price: 24.99,
    oldPrice: 34.99,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80',
    rating: 4.5,
    reviewCount: 630,
    availableStock: 150,
  ),

  // ==================== FASHION ====================
  Product(
    id: 'p9',
    name: 'Classic Heavyweight Pullover Hoodie',
    brand: 'Nike',
    category: 'Fashion',
    description: 'Crafted from soft brushed-back fleece, this everyday essential combines premium comfort with understated athletic styling.',
    price: 65.00,
    oldPrice: 85.00,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80',
    rating: 4.7,
    reviewCount: 780,
    availableStock: 90,
    isFeatured: true,
  ),
  Product(
    id: 'p10',
    name: 'Relaxed Fit Premium Cotton T-Shirt',
    brand: 'Uniqlo',
    category: 'Fashion',
    description: '100% Supima cotton jersey with a smooth texture and clean finish. Tailored crewneck design that retains shape wear after wear.',
    price: 29.90,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80',
    rating: 4.6,
    reviewCount: 1100,
    availableStock: 200,
  ),
  Product(
    id: 'p11',
    name: 'Slim Fit Oxford Button-Down Shirt',
    brand: 'Ralph Lauren',
    category: 'Fashion',
    description: 'An iconic silhouette tailored from breathable woven cotton. Features crisp point collar and signature embroidered motif.',
    price: 89.50,
    oldPrice: 115.00,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
    rating: 4.8,
    reviewCount: 430,
    availableStock: 55,
  ),
  Product(
    id: 'p12',
    name: 'Floral Print Tiered Summer Dress',
    brand: 'Zara',
    category: 'Fashion',
    description: 'Breezy midi dress with romantic floral print, sweetheart neckline, and flattering tiered skirt made of airy viscose blend.',
    price: 59.90,
    oldPrice: 79.90,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80',
    rating: 4.5,
    reviewCount: 360,
    availableStock: 70,
  ),

  // ==================== SHOES ====================
  Product(
    id: 'p13',
    name: 'Air Max 270 Responsive Running Sneakers',
    brand: 'Nike',
    category: 'Shoes',
    description: 'Features Nike’s biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks. Breathable knit upper with snug sock-like fit.',
    price: 159.99,
    oldPrice: 180.00,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    rating: 4.8,
    reviewCount: 2150,
    availableStock: 65,
    isFeatured: true,
  ),
  Product(
    id: 'p14',
    name: 'Ultraboost Light Performance Road Shoes',
    brand: 'Adidas',
    category: 'Shoes',
    description: 'Experience epic energy return with the lightest BOOST midsole ever. Primeknit+ upper delivers tailored support for runs and walks.',
    price: 189.99,
    image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&q=80',
    rating: 4.7,
    reviewCount: 920,
    availableStock: 48,
  ),
  Product(
    id: 'p15',
    name: 'Handcrafted Cap-Toe Oxford Leather Shoes',
    brand: 'Clarks',
    category: 'Shoes',
    description: 'Refined full-grain calfskin leather dress shoes with Goodyear welt construction, cushioned OrthoLite insole, and classic stacked heel.',
    price: 135.00,
    oldPrice: 170.00,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80',
    rating: 4.6,
    reviewCount: 380,
    availableStock: 35,
  ),
  Product(
    id: 'p16',
    name: 'Chuck Taylor All Star High-Top Canvas',
    brand: 'Converse',
    category: 'Shoes',
    description: 'Timeless silhouette featuring durable canvas upper, iconic ankle patch, and diamond pattern rubber outsole.',
    price: 65.00,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    rating: 4.8,
    reviewCount: 1650,
    availableStock: 110,
  ),

  // ==================== BEAUTY ====================
  Product(
    id: 'p17',
    name: 'Hydrating Gentle Foaming Facial Cleanser',
    brand: 'CeraVe',
    category: 'Beauty',
    description: 'Developed with dermatologists, this gentle foaming formula cleanses without disrupting the skin protective moisture barrier.',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80',
    rating: 4.9,
    reviewCount: 2840,
    availableStock: 140,
    isFeatured: true,
  ),
  Product(
    id: 'p18',
    name: 'Hyaluronic Acid 2% + B5 Hydration Serum',
    brand: 'The Ordinary',
    category: 'Beauty',
    description: 'Water-based formula combining low, medium, and high-molecular-weight hyaluronic acid with Vitamin B5 for multi-depth hydration.',
    price: 14.90,
    oldPrice: 19.90,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    rating: 4.7,
    reviewCount: 1920,
    availableStock: 220,
  ),
  Product(
    id: 'p19',
    name: 'Invisible Broad Spectrum Daily Sunscreen SPF 50',
    brand: 'La Roche-Posay',
    category: 'Beauty',
    description: 'Ultra-lightweight invisible fluid sunscreen offering broad-spectrum UVA/UVB protection without greasy residue or white cast.',
    price: 24.50,
    oldPrice: 32.00,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80',
    rating: 4.8,
    reviewCount: 870,
    availableStock: 95,
  ),
  Product(
    id: 'p20',
    name: 'Sauvage Eau de Parfum 100ml',
    brand: 'Dior',
    category: 'Beauty',
    description: 'A sensual and mysterious fragrance infused with notes of radiant Calabrian bergamot, smoky Papua New Guinean vanilla absolute, and amber.',
    price: 145.00,
    oldPrice: 165.00,
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
    rating: 4.9,
    reviewCount: 3400,
    availableStock: 50,
    isFeatured: true,
  ),

  // ==================== HOME & KITCHEN ====================
  Product(
    id: 'p21',
    name: 'VertuoPlus Deluxe Espresso & Coffee Machine',
    brand: 'Nespresso',
    category: 'Home & Kitchen',
    description: 'Centrifusion extraction technology brews five cup sizes of rich, velvety espresso and coffee with luscious crema at the touch of a button.',
    price: 179.00,
    oldPrice: 219.00,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&q=80',
    rating: 4.7,
    reviewCount: 840,
    availableStock: 40,
    isFeatured: true,
  ),
  Product(
    id: 'p22',
    name: 'Precision Temperature Electric Gooseneck Kettle',
    brand: 'Fellow',
    category: 'Home & Kitchen',
    description: 'Sleek matte design with variable temperature control, 60-minute hold mode, and counterbalanced handle for optimal pour-over control.',
    price: 165.00,
    image: 'https://images.unsplash.com/photo-1585862705646-7c9eb145f7c3?w=600&q=80',
    rating: 4.8,
    reviewCount: 620,
    availableStock: 55,
  ),
  Product(
    id: 'p23',
    name: 'Granite Hard-Anodized Nonstick 10-Inch Skillet',
    brand: 'Calphalon',
    category: 'Home & Kitchen',
    description: 'Heavy-gauge hard-anodized aluminum pan with multilayer nonstick surface for effortless food release and durable daily cooking.',
    price: 49.99,
    oldPrice: 65.00,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&q=80',
    rating: 4.6,
    reviewCount: 410,
    availableStock: 85,
  ),
  Product(
    id: 'p24',
    name: 'Aroma Ultrasonic Essential Oil Diffuser',
    brand: 'Muji',
    category: 'Home & Kitchen',
    description: 'Disperses ultrasonic mist accompanied by soothing ambient LED illumination. Transforms any room into a calm, tranquil sanctuary.',
    price: 39.50,
    oldPrice: 52.00,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    rating: 4.7,
    reviewCount: 520,
    availableStock: 75,
  ),

  // ==================== ACCESSORIES ====================
  Product(
    id: 'p25',
    name: 'Handmade Bifold Full-Grain Leather Wallet',
    brand: 'Bellroy',
    category: 'Accessories',
    description: 'Engineered slim profile holding up to 12 cards and flat bills with RFID theft protection and premium eco-tanned leather finish.',
    price: 79.00,
    oldPrice: 95.00,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80',
    rating: 4.8,
    reviewCount: 670,
    availableStock: 90,
    isFeatured: true,
  ),
  Product(
    id: 'p26',
    name: 'Classic Aviator Polarized Sunglasses',
    brand: 'Ray-Ban',
    category: 'Accessories',
    description: 'Original teardrop crystal lenses with gold-tone metal frame providing 100% UV protection and exceptional glare reduction.',
    price: 169.00,
    oldPrice: 199.00,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80',
    rating: 4.8,
    reviewCount: 1420,
    availableStock: 70,
    isFeatured: true,
  ),
  Product(
    id: 'p27',
    name: 'Leather Belt with Brushed Nickel Buckle',
    brand: 'Fossil',
    category: 'Accessories',
    description: 'Crafted from 100% genuine full-grain leather with clean edge detailing and durable solid metal prong buckle.',
    price: 38.00,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&q=80',
    rating: 4.5,
    reviewCount: 290,
    availableStock: 120,
  ),
  Product(
    id: 'p28',
    name: 'Minimalist Titanium Key Organizer & Clip',
    brand: 'KeySmart',
    category: 'Accessories',
    description: 'Eliminate noisy, bulky keyrings with this aircraft-grade titanium compact holder accommodating up to 8 keys cleanly.',
    price: 28.00,
    oldPrice: 35.00,
    image: 'https://images.unsplash.com/photo-1582142407894-ec85a1260a46?w=600&q=80',
    rating: 4.6,
    reviewCount: 310,
    availableStock: 160,
  ),

  // ==================== BAGS ====================
  Product(
    id: 'p29',
    name: 'Everyday Weatherproof Travel Backpack 20L',
    brand: 'Peak Design',
    category: 'Bags',
    description: 'Award-winning versatile everyday bag with dedicated padded 15-inch laptop compartment, MagLatch hardware, and weatherproof 400D shell.',
    price: 199.95,
    oldPrice: 229.95,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    rating: 4.9,
    reviewCount: 980,
    availableStock: 45,
    isFeatured: true,
  ),
  Product(
    id: 'p30',
    name: 'Heritage Weekend Duffel Bag with Shoe Pocket',
    brand: 'Herschel',
    category: 'Bags',
    description: 'Classic barrel duffel with signature striped fabric liner, two-way waterproof zipper, reinforced carry handles, and ventilated shoe tunnel.',
    price: 90.00,
    oldPrice: 110.00,
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80',
    rating: 4.7,
    reviewCount: 510,
    availableStock: 60,
  ),
  Product(
    id: 'p31',
    name: 'Crossbody Utility Messenger Sling',
    brand: 'Aer',
    category: 'Bags',
    description: 'Streamlined sling bag tailored for daily carry essentials. Features Cordura ballistic nylon and Fidlock magnetic buckle strap.',
    price: 75.00,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80',
    rating: 4.6,
    reviewCount: 340,
    availableStock: 80,
  ),

  // ==================== WATCHES ====================
  Product(
    id: 'p32',
    name: 'Apple Watch Series 9 GPS 45mm Starlight',
    brand: 'Apple',
    category: 'Watches',
    description: 'Smarter, brighter, and mightier with the S9 SiP. Magical double tap gesture control, blood oxygen sensor, and always-on Retina display.',
    price: 399.00,
    oldPrice: 429.00,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    rating: 4.9,
    reviewCount: 2310,
    availableStock: 50,
    isFeatured: true,
  ),
  Product(
    id: 'p33',
    name: 'Minimalist Chronograph Mesh Watch',
    brand: 'Fossil',
    category: 'Watches',
    description: 'Stainless steel case featuring quartz chronograph movement, deep sunray dial, date window, and easily interchangeable steel mesh band.',
    price: 139.00,
    oldPrice: 175.00,
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80',
    rating: 4.6,
    reviewCount: 420,
    availableStock: 65,
  ),
  Product(
    id: 'p34',
    name: 'Seiko 5 Sports Automatic Steel Watch',
    brand: 'Seiko',
    category: 'Watches',
    description: 'Legendary automatic 24-jewel movement with day/date display, unidirectional rotating bezel, and 100m water resistance.',
    price: 275.00,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80',
    rating: 4.8,
    reviewCount: 710,
    availableStock: 30,
    isFeatured: true,
  ),

  // ==================== GAMING ====================
  Product(
    id: 'p35',
    name: 'G Pro X Superlight Wireless Gaming Mouse',
    brand: 'Logitech G',
    category: 'Gaming',
    description: 'Meticulously engineered in collaboration with world-leading esports pros. Under 63 grams with HERO 25K sensor and zero-additive PTFE feet.',
    price: 129.99,
    oldPrice: 159.99,
    image: 'https://images.unsplash.com/photo-1527814050087-179337eb13ee?w=600&q=80',
    rating: 4.9,
    reviewCount: 1620,
    availableStock: 60,
    isFeatured: true,
  ),
  Product(
    id: 'p36',
    name: 'BlackWidow V4 Pro RGB Mechanical Keyboard',
    brand: 'Razer',
    category: 'Gaming',
    description: 'Immersive underglow RGB with Razer Yellow linear mechanical switches, multi-function command dial, and plush leatherette magnetic wrist rest.',
    price: 199.99,
    oldPrice: 229.99,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=600&q=80',
    rating: 4.8,
    reviewCount: 940,
    availableStock: 45,
  ),
  Product(
    id: 'p37',
    name: 'DualSense Wireless Controller Midnight Black',
    brand: 'Sony PlayStation',
    category: 'Gaming',
    description: 'Feel your in-game actions and environment simulated through haptic feedback and dynamic adaptive triggers with built-in microphone.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&q=80',
    rating: 4.9,
    reviewCount: 3800,
    availableStock: 110,
    isFeatured: true,
  ),
  Product(
    id: 'p38',
    name: 'Arctis Nova Pro Wireless Multi-System Headset',
    brand: 'SteelSeries',
    category: 'Gaming',
    description: 'Almighty Audio with premium high-fidelity drivers, active noise cancellation, and hot-swappable dual-battery continuous play system.',
    price: 329.99,
    oldPrice: 349.99,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80',
    rating: 4.7,
    reviewCount: 520,
    availableStock: 35,
  ),

  // ==================== SPORTS ====================
  Product(
    id: 'p39',
    name: 'Insulated 32oz Wide Mouth Water Bottle',
    brand: 'Hydro Flask',
    category: 'Sports',
    description: 'TempShield double-wall vacuum insulation keeps beverages cold for up to 24 hours. Durable 18/8 pro-grade stainless steel with leakproof Flex Cap.',
    price: 44.95,
    oldPrice: 54.95,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    rating: 4.9,
    reviewCount: 1890,
    availableStock: 180,
    isFeatured: true,
  ),
  Product(
    id: 'p40',
    name: 'Pro Non-Slip Cushioned Yoga Mat 6mm',
    brand: 'Lululemon',
    category: 'Sports',
    description: 'Dual-textured dense natural rubber construction offering superior grip and unmatched joint cushioning for yoga, pilates, and floor workouts.',
    price: 78.00,
    oldPrice: 98.00,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80',
    rating: 4.8,
    reviewCount: 640,
    availableStock: 75,
  ),
  Product(
    id: 'p41',
    name: 'Adjustable Quick-Select Dumbbell Pair 50lbs',
    brand: 'Bowflex',
    category: 'Sports',
    description: 'Rapid dial system lets you adjust resistance from 5 to 50 lbs in 2.5 lb increments, replacing 15 sets of weights in one compact footprint.',
    price: 379.00,
    oldPrice: 429.00,
    image: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=600&q=80',
    rating: 4.7,
    reviewCount: 880,
    availableStock: 25,
  ),
  Product(
    id: 'p42',
    name: 'Speed Jump Rope with Ball Bearings',
    brand: 'Gymshark',
    category: 'Sports',
    description: 'Lightweight aluminum anti-slip handles and 360-degree dual bearing system for ultra-fast rotations during cardio and cross-training.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80',
    rating: 4.6,
    reviewCount: 390,
    availableStock: 130,
  ),
];
