import 'product.dart';

final List<Product> dummyProducts = [
  // ==================== 1. ELECTRONICS (10 PRODUCTS) ====================
  const Product(
    id: 'prod_elec_01',
    name: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'Headphones',
    description: 'Industry-leading noise cancellation optimized by two processors and 8 microphones. Up to 30-hour battery life with 3-minute quick charging for 3 hours playback. Ultra-lightweight soft-fit leather.',
    price: 89999.0,
    oldPrice: 99999.0,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 1420,
    availableStock: 28,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#D4D4D8'],
    sizes: [],
    tags: ['sony', 'headphones', 'wireless', 'noise-cancelling', 'bluetooth', 'audio'],
    specifications: {
      'Battery Life': '30 Hours',
      'Connectivity': 'Bluetooth 5.2 / 3.5mm Aux',
      'Noise Cancelling': 'Dual Processor QN1 & V1',
      'Charging Port': 'USB-C Fast Charging',
      'Warranty': '1 Year Official Sony Pakistan Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days. Insured TCS delivery across Pakistan.',
    sellerName: 'Sony Official Flagship Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_elec_02',
    name: 'Bose SoundLink Flex Waterproof Bluetooth Speaker',
    brand: 'Bose',
    category: 'Electronics',
    subcategory: 'Speakers',
    description: 'State-of-the-art portable speaker engineered for astonishing crisp audio and deep bass. Rugged silicone exterior with IP67 waterproof and dustproof rating, engineered to float in water.',
    price: 34999.0,
    oldPrice: 38999.0,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 890,
    availableStock: 45,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#2563EB', '#F43F5E'],
    sizes: [],
    tags: ['bose', 'speaker', 'bluetooth', 'waterproof', 'outdoor', 'audio'],
    specifications: {
      'Playtime': '12 Hours per charge',
      'Water Resistance': 'IP67 Waterproof & Dustproof',
      'PositionIQ Tech': 'Auto-detects orientation for optimal sound',
      'Weight': '590g',
      'Warranty': '1 Year International Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days. Free shipping.',
    sellerName: 'Bose Premier Partner PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_elec_03',
    name: 'Anker 737 Power Bank PowerCore 24000mAh 140W',
    brand: 'Anker',
    category: 'Electronics',
    subcategory: 'Power Banks',
    description: 'Ultra-powerful high-capacity portable power bank equipped with 140W two-way fast charging and smart digital display showing output wattage and battery health in real-time.',
    price: 24999.0,
    oldPrice: 28999.0,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 650,
    availableStock: 60,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    isDeal: true,
    colors: ['#1E293B'],
    sizes: [],
    tags: ['anker', 'power bank', 'charger', 'fast charging', 'usb-c', 'laptop charger'],
    specifications: {
      'Capacity': '24,000 mAh',
      'Max Output': '140W Power Delivery 3.1',
      'Ports': '2x USB-C, 1x USB-A',
      'Smart Display': 'Color TFT Battery Gauge',
      'Warranty': '18 Months Official Warranty',
    },
    deliveryInfo: 'Estimated delivery: 1–2 business days in Lahore, Karachi & Islamabad.',
    sellerName: 'Anker Direct Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_elec_04',
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    brand: 'Logitech',
    category: 'Electronics',
    subcategory: 'Accessories',
    description: 'An icon remastered. Quiet click switches with 8K DPI track-on-glass sensor. MagSpeed electromagnetic scrolling wheel scrolls 1,000 lines per second with pixel-precise control.',
    price: 26499.0,
    oldPrice: 29999.0,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 1120,
    availableStock: 35,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#E2E8F0'],
    sizes: [],
    tags: ['logitech', 'mouse', 'mx master', 'office', 'wireless', 'ergonomic'],
    specifications: {
      'Sensor': 'Darkfield 8,000 DPI',
      'Battery Life': 'Up to 70 days on full charge',
      'Multi-Device': 'Pair up to 3 computers via Flow',
      'Connection': 'Bluetooth Low Energy & Logi Bolt',
      'Warranty': '1 Year Local Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Logitech Authorized Partner',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_elec_05',
    name: 'Keychron K2 Pro QMK/VIA Wireless Mechanical Keyboard',
    brand: 'Keychron',
    category: 'Electronics',
    subcategory: 'Accessories',
    description: '75% compact wireless custom mechanical keyboard with hot-swappable Keychron K Pro brown switches, pre-lubed screw-in stabilizers, and South-facing RGB backlighting.',
    price: 27999.0,
    oldPrice: 31999.0,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 430,
    availableStock: 20,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#1E293B'],
    sizes: [],
    tags: ['keyboard', 'mechanical keyboard', 'keychron', 'wireless', 'rgb', 'gaming'],
    specifications: {
      'Layout': '75% (84 Keys)',
      'Switches': 'Keychron K Pro Brown (Tactile)',
      'Battery': '4,000 mAh Rechargeable Li-polymer',
      'Compatibility': 'macOS / Windows / Linux / iOS',
      'Warranty': '1 Year Replacement Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'MechKeys Pakistan',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_elec_06',
    name: 'Sony SRS-XB100 Compact Travel Speaker',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'Speakers',
    description: 'Super compact body with Sound Diffusion Processor for expansive surround sound. Multiway strap lets you hang it from your backpack or bicycle handle.',
    price: 13499.0,
    oldPrice: 15499.0,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    rating: 4.6,
    reviewCount: 380,
    availableStock: 50,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#10B981', '#3B82F6'],
    sizes: [],
    tags: ['sony', 'speaker', 'portable', 'compact', 'waterproof'],
    specifications: {
      'Battery Life': 'Up to 16 Hours',
      'Protection': 'IP67 Waterproof & Dustproof',
      'Echo Cancelling': 'Hands-free crystal calls',
      'Warranty': '1 Year Sony Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Sony Official Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_elec_07',
    name: 'UGREEN Nexode 100W 4-Port GaN Fast Wall Charger',
    brand: 'UGREEN',
    category: 'Electronics',
    subcategory: 'Accessories',
    description: 'Gallium Nitride (GaN) fast charger with 3 USB-C and 1 USB-A ports. Powers a MacBook Pro, iPhone, iPad, and earbuds at maximum speed simultaneously.',
    price: 14999.0,
    oldPrice: 17999.0,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    rating: 4.8,
    reviewCount: 710,
    availableStock: 85,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#475569'],
    sizes: [],
    tags: ['ugreen', 'charger', 'gan', 'fast charging', 'macbook', '100w'],
    specifications: {
      'Total Output': '100W Max',
      'Ports': '3x USB-C, 1x USB-A',
      'Technology': 'GaN II Fast Charging',
      'Safety': 'Thermal Guard 2.0 temperature sensor',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'UGREEN Authorized Store',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_elec_08',
    name: 'Sennheiser Momentum 4 Wireless Studio Headphones',
    brand: 'Sennheiser',
    category: 'Electronics',
    subcategory: 'Headphones',
    description: 'Audiophile-inspired 42mm transducer system delivering exceptional acoustics with brilliant clarity and musical nuance. Unrivaled 60-hour marathon battery life.',
    price: 79999.0,
    oldPrice: 89999.0,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    rating: 4.9,
    reviewCount: 520,
    availableStock: 15,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#F8FAFC'],
    sizes: [],
    tags: ['sennheiser', 'audiophile', 'headphones', 'wireless', 'momentum 4'],
    specifications: {
      'Battery Life': '60 Hours continuous playback',
      'Driver Size': '42mm Audiophile Dynamic Transducers',
      'Codecs': 'aptX Adaptive, AAC, SBC',
      'Warranty': '2 Years International Sennheiser Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'HiFi Lounge PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_elec_09',
    name: 'Marshall Emberton II Portable Bluetooth Speaker',
    brand: 'Marshall',
    category: 'Electronics',
    subcategory: 'Speakers',
    description: 'Iconic Marshall rock-and-roll styling with multi-directional True Stereophonic sound. 30+ hours of portable playtime on a single charge with IP67 durability.',
    price: 48999.0,
    oldPrice: 54999.0,
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80',
    rating: 4.8,
    reviewCount: 940,
    availableStock: 22,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#D97706'],
    sizes: [],
    tags: ['marshall', 'speaker', 'vintage', 'rock', 'bluetooth', 'audio'],
    specifications: {
      'Playtime': '30+ Hours',
      'Water Rating': 'IP67 Water and Dust resistant',
      'Sound Feature': 'True Stereophonic 360 sound',
      'Weight': '700g',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Audio Haven Pakistan',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_elec_10',
    name: 'Apple AirPods Pro 2nd Gen with USB-C MagSafe Case',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Earbuds',
    description: 'Next-level Active Noise Cancellation with Apple H2 headphone chip. Adaptive Audio automatically blends Transparency and Active Noise Cancellation.',
    price: 68999.0,
    oldPrice: 74999.0,
    image: 'https://images.unsplash.com/photo-1572569533902-3e0e9328bcb2?w=800&q=80',
    rating: 4.9,
    reviewCount: 3120,
    availableStock: 75,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#FFFFFF'],
    sizes: [],
    tags: ['apple', 'airpods', 'airpods pro', 'earbuds', 'wireless', 'noise cancelling'],
    specifications: {
      'Chipset': 'Apple H2 chip / U1 in Case',
      'Case Charging': 'USB-C, MagSafe, Apple Watch charger',
      'Battery Life': 'Up to 30 hours with case',
      'Warranty': '1 Year Apple Official Warranty',
    },
    deliveryInfo: 'Estimated delivery: 1–2 business days. Express TCS courier.',
    sellerName: 'Apple Authorized Reseller',
    sellerRating: 4.9,
  ),

  // ==================== 2. MOBILES (10 PRODUCTS) ====================
  const Product(
    id: 'prod_mob_01',
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    brand: 'Apple',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'Forged in aerospace-grade titanium with the breakthrough A17 Pro 3nm chip. 48MP Main camera with 5x optical telephoto lens and customizable Action button. PTA Approved with official warranty.',
    price: 439999.0,
    oldPrice: 469999.0,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 2450,
    availableStock: 18,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78716C', '#0F172A', '#F5F5F4'],
    sizes: [],
    tags: ['apple', 'iphone', 'iphone 15 pro max', 'titanium', 'smartphone', 'flagship'],
    specifications: {
      'Processor': 'Apple A17 Pro 3nm',
      'Display': '6.7" Super Retina XDR OLED 120Hz ProMotion',
      'Camera': '48MP Main + 12MP Ultra-wide + 12MP 5x Telephoto',
      'PTA Status': 'PTA Approved Official',
      'Warranty': '1 Year Apple Mercantile Warranty',
    },
    deliveryInfo: 'Free secure hand delivery in major cities. 2–3 days nationwide.',
    sellerName: 'Mercantile Official Apple Partner',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_mob_02',
    name: 'Samsung Galaxy S24 Ultra 5G 512GB Titanium Black',
    brand: 'Samsung',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'Galaxy AI is here. Circle to Search, Live Call Translation, and Note Assist. Features a 200MP camera with Quad Tele system, Snapdragon 8 Gen 3 for Galaxy, and built-in S Pen.',
    price: 389999.0,
    oldPrice: 419999.0,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    rating: 4.8,
    reviewCount: 1840,
    availableStock: 24,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#94A3B8'],
    sizes: [],
    tags: ['samsung', 'galaxy s24 ultra', 'galaxy ai', 's pen', '5g', 'flagship'],
    specifications: {
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
      'Display': '6.8" Dynamic AMOLED 2X 120Hz 2600 nits',
      'Camera': '200MP + 50MP 5x + 10MP 3x + 12MP Ultra-wide',
      'PTA Status': 'Official PTA Approved',
      'Warranty': '1 Year Samsung Pakistan Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Samsung Official Flagship Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_mob_03',
    name: 'Google Pixel 8 Pro 128GB Obsidian Black',
    brand: 'Google',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'Powered by Google Tensor G3 with industry-best computational photography, Magic Editor, Best Take, and guaranteed 7 years of Android OS and security upgrades.',
    price: 219999.0,
    oldPrice: 239999.0,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351cb31b?w=800&q=80',
    rating: 4.7,
    reviewCount: 910,
    availableStock: 14,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#38BDF8'],
    sizes: [],
    tags: ['google', 'pixel 8 pro', 'tensor g3', 'android', 'camera phone'],
    specifications: {
      'Processor': 'Google Tensor G3 & Titan M2 security',
      'Display': '6.7" Super Actua OLED 1-120Hz',
      'Camera': '50MP Octa PD + 48MP Ultra-wide + 48MP 5x Telephoto',
      'PTA Status': 'PTA Approved',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Pixel Store Pakistan',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_mob_04',
    name: 'Apple iPad Air 11-inch M2 Chip 128GB Space Grey',
    brand: 'Apple',
    category: 'Mobiles',
    subcategory: 'Tablets',
    description: 'Redesigned iPad Air turbocharged by the incredibly fast Apple M2 chip. Features Liquid Retina display, landscape 12MP front camera, and Apple Pencil Pro support.',
    price: 184999.0,
    oldPrice: 199999.0,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    rating: 4.9,
    reviewCount: 780,
    availableStock: 25,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#475569', '#38BDF8'],
    sizes: [],
    tags: ['apple', 'ipad', 'ipad air', 'm2', 'tablet', 'apple pencil'],
    specifications: {
      'Processor': 'Apple M2 8-core CPU / 10-core GPU',
      'Display': '11-inch Liquid Retina with True Tone',
      'Storage': '128GB NVMe High-speed',
      'Warranty': '1 Year Apple Official Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Apple Authorized Partner',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_mob_05',
    name: 'Samsung Galaxy Tab S9 FE 10.9-inch with S Pen',
    brand: 'Samsung',
    category: 'Mobiles',
    subcategory: 'Tablets',
    description: 'Vibrant 10.9-inch 90Hz display with water and dust-resistant IP68 body and IP68 S Pen included in the box. Dual AKG stereo speakers for immersive movies and sketching.',
    price: 119999.0,
    oldPrice: 134999.0,
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80',
    rating: 4.7,
    reviewCount: 460,
    availableStock: 30,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#334155', '#A7F3D0'],
    sizes: [],
    tags: ['samsung', 'tablet', 'tab s9 fe', 's pen', 'android tablet'],
    specifications: {
      'Screen': '10.9" WQXGA 90Hz Smooth Display',
      'Stylus': 'S Pen Included (IP68 rated)',
      'Battery': '8,000 mAh with 45W fast charge support',
      'Warranty': '1 Year Samsung Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Samsung Direct PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_mob_06',
    name: 'Xiaomi 14 Ultra 5G Leica Quad Camera 512GB',
    brand: 'Xiaomi',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'Co-engineered with Leica. 1-inch LYT-900 sensor with stepless variable aperture f/1.63-f/4.0. Snapdragon 8 Gen 3, WQHD+ 120Hz AMOLED, and 90W HyperCharge.',
    price: 319999.0,
    oldPrice: 349999.0,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    rating: 4.8,
    reviewCount: 310,
    availableStock: 12,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#F8FAFC'],
    sizes: [],
    tags: ['xiaomi', 'xiaomi 14 ultra', 'leica', 'camera phone', 'flagship'],
    specifications: {
      'Optics': 'Leica Quad 50MP Cameras with 1-inch sensor',
      'Chip': 'Snapdragon 8 Gen 3 (4nm)',
      'Charging': '90W Wired + 80W Wireless HyperCharge',
      'PTA Status': 'PTA Approved',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Xiaomi Flagship Store',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_mob_07',
    name: 'Baseus 65W GaN5 Pro USB-C Fast Charger with Cable',
    brand: 'Baseus',
    category: 'Mobiles',
    subcategory: 'Mobile Accessories',
    description: 'Compact 3-port travel wall charger compatible with iPhone fast charge, Samsung Super Fast Charging 2.0, and 65W USB-C laptops. Includes 100W 1.2m Type-C cable.',
    price: 8499.0,
    oldPrice: 9999.0,
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&q=80',
    rating: 4.7,
    reviewCount: 1140,
    availableStock: 120,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#F8FAFC'],
    sizes: [],
    tags: ['baseus', 'charger', 'type c', '65w', 'fast charging'],
    specifications: {
      'Total Watts': '65W GaN5 Pro',
      'Ports': '2x Type-C, 1x USB-A',
      'Included': '100W E-Marker Type-C braided cable',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Baseus Official PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_mob_08',
    name: 'Spigen Tough Armor Case for iPhone 15 Pro Max',
    brand: 'Spigen',
    category: 'Mobiles',
    subcategory: 'Mobile Accessories',
    description: 'Dual-layer air cushion technology for extreme drop defense. Built-in reinforced kickstand for hands-free landscape movie viewing. Raised lips protect screen and camera lenses.',
    price: 6499.0,
    oldPrice: 7999.0,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80',
    rating: 4.9,
    reviewCount: 890,
    availableStock: 65,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#475569'],
    sizes: [],
    tags: ['spigen', 'iphone case', 'tough armor', 'protective case'],
    specifications: {
      'Material': 'TPU + Polycarbonate hard shell',
      'Certification': 'Mil-grade drop tested [MIL-STD 810G-516.6]',
      'Features': 'Integrated kickstand + Air Cushion',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Spigen Direct Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_mob_09',
    name: 'Joyroom MagSafe 15W Qi2 Magnetic Wireless Car Mount',
    brand: 'Joyroom',
    category: 'Mobiles',
    subcategory: 'Mobile Accessories',
    description: 'Upgraded N52 neodymium magnetic ring firmly locks phone through bumpy roads. Automatic Qi2 15W fast wireless charging with 360-degree ball joint air vent clamp.',
    price: 5499.0,
    oldPrice: 6999.0,
    image: 'https://images.unsplash.com/photo-1584285418504-006a86c67ef8?w=800&q=80',
    rating: 4.6,
    reviewCount: 420,
    availableStock: 90,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: [],
    tags: ['car mount', 'magsafe', 'wireless charger', 'joyroom', 'accessories'],
    specifications: {
      'Mount Type': 'Steel hook air vent clip',
      'Charging Output': '15W Fast Wireless',
      'Magnetic Strength': '1800g holding force',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Joyroom Official Store',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_mob_10',
    name: 'Samsung 45W Super Fast Charger 2.0 with 5A Cable',
    brand: 'Samsung',
    category: 'Mobiles',
    subcategory: 'Mobile Accessories',
    description: 'Official Samsung Power Delivery 3.0 wall adapter for Galaxy S24 Ultra, S23+, and Tab S9. Charges from 0% to 70% in just 30 minutes.',
    price: 7999.0,
    oldPrice: 9499.0,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    rating: 4.8,
    reviewCount: 1650,
    availableStock: 110,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#000000', '#FFFFFF'],
    sizes: [],
    tags: ['samsung', 'fast charger', '45w', 's24 ultra', 'original'],
    specifications: {
      'Wattage': '45W Super Fast Charging 2.0',
      'Cable': 'Original Samsung 5A 1.8m Type-C to Type-C',
      'Warranty': '6 Months Official Warranty',
    },
    deliveryInfo: 'Estimated delivery: 1–2 business days.',
    sellerName: 'Samsung Official Flagship Store',
    sellerRating: 4.9,
  ),

  // ==================== 3. FASHION (12 PRODUCTS) ====================
  const Product(
    id: 'prod_fash_01',
    name: "J. Junaid Jamshed Men's Premium Raw Silk Embroidered Kurta",
    brand: 'J.',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'Exquisite tailored raw silk kurta featuring subtle tone-on-tone ban collar embroidery and mother-of-pearl buttons. Perfect for Eid, weddings, and traditional festive gatherings.',
    price: 8990.0,
    oldPrice: 11990.0,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 620,
    availableStock: 45,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#1E3A8A', '#F5F5F4'],
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['j.', 'kurta', 'eastern wear', 'men fashion', 'pakistani festive', 'eid'],
    specifications: {
      'Fabric': '100% Premium Blended Raw Silk',
      'Fit': 'Classic Straight Fit',
      'Collar': 'Hand-embroidered Ban Collar',
      'Care': 'Dry Clean Recommended',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days across Pakistan.',
    sellerName: 'J. Junaid Jamshed Official',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_fash_02',
    name: 'Khaadi 3-Piece Stitched Embroidered Lawn Suit',
    brand: 'Khaadi',
    category: 'Fashion',
    subcategory: "Women's Clothing",
    description: 'Intricately embroidered printed lawn shirt paired with matching dyed cambric trousers and a lightweight digital printed chiffon dupatta. Breathable summer luxury.',
    price: 9490.0,
    oldPrice: 12490.0,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 1450,
    availableStock: 35,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    isDeal: true,
    colors: ['#047857', '#9333EA', '#E11D48'],
    sizes: ['XS', 'S', 'M', 'L'],
    tags: ['khaadi', 'lawn suit', 'stitched', 'women fashion', 'embroidered', 'eastern wear'],
    specifications: {
      'Shirt': 'Embroidered Lawn (3 Meters)',
      'Dupatta': 'Digital Printed Pure Chiffon (2.5 Meters)',
      'Trouser': 'Dyed Cambric Cotton',
      'Season': 'Spring / Summer 2026',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Khaadi Official Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_fash_03',
    name: 'Charcoal Slim-Fit 100% Merino Wool Blazer Jacket',
    brand: 'Charcoal',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'Structured notch lapel blazer crafted from imported Italian wool blend. Features half-canvas construction, horn buttons, double vent back, and interior passport pocket.',
    price: 24990.0,
    oldPrice: 29990.0,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
    rating: 4.7,
    reviewCount: 380,
    availableStock: 22,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#334155'],
    sizes: ['38R', '40R', '42R', '44R'],
    tags: ['blazer', 'charcoal', 'suit jacket', 'formal', 'men fashion', 'office'],
    specifications: {
      'Material': '70% Wool, 30% Silk-Touch Poly Blend',
      'Lining': 'Breathable Bemberg Silk',
      'Cut': 'Modern European Slim Fit',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Charcoal Official',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_fash_04',
    name: 'Outfitters Heavyweight Relaxed Oversized Graphic Hoodie',
    brand: 'Outfitters',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: '450 GSM ultra-soft brushed fleece pullover hoodie with dropped shoulders, kangaroo pocket, and high-density typography puff print on the chest and back.',
    price: 5490.0,
    oldPrice: 6990.0,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
    rating: 4.6,
    reviewCount: 890,
    availableStock: 70,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#64748B', '#F59E0B'],
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['outfitters', 'hoodie', 'oversized', 'streetwear', 'fleece', 'winter'],
    specifications: {
      'Weight': '450 GSM Heavy Fleece',
      'Composition': '80% Cotton, 20% Polyester',
      'Wash Care': 'Machine wash cold inside out',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Outfitters Flagship',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_fash_05',
    name: 'Sapphire Ready-to-Wear Solid Viscose Tunic Kurti',
    brand: 'Sapphire',
    category: 'Fashion',
    subcategory: "Women's Clothing",
    description: 'Sophisticated solid dyed viscose tunic featuring delicate lace inserts along the sleeves and hemline. Designed for effortless everyday chic styling.',
    price: 4990.0,
    oldPrice: 6490.0,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
    rating: 4.7,
    reviewCount: 520,
    availableStock: 50,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0D9488', '#E11D48', '#D97706'],
    sizes: ['XS', 'S', 'M', 'L'],
    tags: ['sapphire', 'kurti', 'pret', 'ready to wear', 'women fashion'],
    specifications: {
      'Fabric': 'Premium Viscose Slub',
      'Length': '38 inches (Standard Knee Length)',
      'Style': 'Straight Cut with Side Slits',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Sapphire Retail PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_fash_06',
    name: 'Levi’s 511 Slim Fit Stretch Denim Jeans (Dark Indigo)',
    brand: "Levi's",
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'The modern slim fit with room to move. Cut close through the seat and thigh with a slim leg. Engineered with Levi’s Flex advanced stretch technology for all-day comfort.',
    price: 11990.0,
    oldPrice: 14490.0,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
    rating: 4.8,
    reviewCount: 1120,
    availableStock: 55,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#1E3A8A', '#0F172A'],
    sizes: ['30x32', '32x32', '34x32', '36x32'],
    tags: ['levis', 'jeans', 'denim', '511 slim', 'pants', 'men clothing'],
    specifications: {
      'Fit': '511 Slim Fit',
      'Fabric': '99% Cotton, 1% Elastane',
      'Fly': 'Zip fly with metal shank closure',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: "Levi's Official Store",
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_fash_07',
    name: "Alkaram Studio Men's Wash & Wear Unstitched Fabric 4m",
    brand: 'Alkaram',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'Wrinkle-resistant soft wash-and-wear unstitched fabric designed specifically for all-season shalwar kameez. Features crisp fall, smooth texture, and breathable weave.',
    price: 4490.0,
    oldPrice: 5490.0,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
    rating: 4.7,
    reviewCount: 760,
    availableStock: 90,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#FFFFFF', '#E2E8F0', '#1E293B', '#78350F'],
    sizes: ['4 Meters Standard Cut'],
    tags: ['alkaram', 'unstitched', 'wash and wear', 'shalwar kameez', 'eastern'],
    specifications: {
      'Length': '4.0 Meters (Standard Men Cut)',
      'Width': '54 inches',
      'Fabric': 'Wash & Wear Poly-Viscose blend',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Alkaram Studio',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_fash_08',
    name: 'Generation Festive Embroidered Jacquard Peplum Shirt',
    brand: 'Generation',
    category: 'Fashion',
    subcategory: "Women's Clothing",
    description: 'Flared peplum silhouette cut from lustrous golden jacquard with contrasting resham threadwork across the yoke and tassels along the neckline.',
    price: 7998.0,
    oldPrice: 9998.0,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&q=80',
    rating: 4.7,
    reviewCount: 310,
    availableStock: 25,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#D97706', '#991B1B'],
    sizes: ['8 (S)', '10 (M)', '12 (L)'],
    tags: ['generation', 'peplum', 'jacquard', 'festive', 'party wear'],
    specifications: {
      'Fabric': 'Zari Woven Jacquard',
      'Embellishment': 'Handcrafted Resham & Tassels',
      'Care': 'Gentle Hand Wash',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Generation Official',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_fash_09',
    name: 'Uniworth Formal Executive Non-Iron Cotton Shirt',
    brand: 'Uniworth',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: '100% Egyptian Giza long-staple cotton non-iron formal shirt with spread collar and French cuffs. Remains crisp and wrinkle-free throughout long business days.',
    price: 5995.0,
    oldPrice: 7495.0,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
    rating: 4.8,
    reviewCount: 640,
    availableStock: 40,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#FFFFFF', '#BAE6FD', '#E2E8F0'],
    sizes: ['15 (S)', '15.5 (M)', '16 (L)', '16.5 (XL)'],
    tags: ['uniworth', 'formal shirt', 'cotton', 'executive', 'non iron', 'office'],
    specifications: {
      'Yarn': '100s Two-Ply Egyptian Giza Cotton',
      'Collar': 'English Spread Collar with Stiffeners',
      'Treatment': 'Permanent Nano Non-Iron Finish',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Uniworth Dress Co.',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_fash_10',
    name: 'Bona Papa Premium Cashmere Winter Shawl 2.5m',
    brand: 'Heritage Kashmir',
    category: 'Fashion',
    subcategory: 'Eastern Wear',
    description: 'Traditional handcrafted pure cashmere wool shawl featuring intricate sozni needle embroidery border. Luxurious warmth and featherlight drape for cold winter evenings.',
    price: 18999.0,
    oldPrice: 23999.0,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80',
    rating: 4.9,
    reviewCount: 220,
    availableStock: 16,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78350F', '#1E293B', '#F5F5F4'],
    sizes: ['2.5 Meters (One Size)'],
    tags: ['cashmere', 'shawl', 'pashmina', 'winter', 'heritage', 'men shawl'],
    specifications: {
      'Composition': '100% Grade-A Cashmere Wool',
      'Weave': 'Fine Twill Weave with Eyelash Fringe',
      'Dimensions': '100 cm x 250 cm',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Heritage Textiles Peshawar',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_fash_11',
    name: "Edenrobe Boys' Festive Jacquard Waistcoat",
    brand: 'Edenrobe',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'Tailored bandhgala waistcoat in textured self-print jacquard with brass metallic buttons and welt pockets. Perfect to layer over any kurta shalwar.',
    price: 4290.0,
    oldPrice: 5290.0,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80',
    rating: 4.6,
    reviewCount: 390,
    availableStock: 35,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['waistcoat', 'edenrobe', 'festive', 'eid', 'kurta layer'],
    specifications: {
      'Style': 'Mandarin Bandhgala Cut',
      'Fabric': 'Textured Poly-Jacquard',
      'Buttons': 'Embossed Metal Buttons',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Edenrobe Official',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_fash_12',
    name: 'Zara Men Lightweight Water-Repellent Puffer Vest',
    brand: 'Zara',
    category: 'Fashion',
    subcategory: "Men's Clothing",
    description: 'Thermal insulated sleeveless puffer gilet with stand collar, hidden zip closure, and interior fleece lined pockets. Light enough to layer over hoodies and knitwear.',
    price: 13990.0,
    oldPrice: 16990.0,
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80',
    rating: 4.7,
    reviewCount: 480,
    availableStock: 28,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#334155'],
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['zara', 'puffer vest', 'gilet', 'winter fashion', 'outerwear'],
    specifications: {
      'Shell': '100% Water-repellent Recycled Polyamide',
      'Insulation': 'Thermolite Eco-Down Microfiber',
      'Closure': 'Two-way front zipper',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Urban Import Hub PK',
    sellerRating: 4.8,
  ),

  // ==================== 4. SHOES (9 PRODUCTS) ====================
  const Product(
    id: 'prod_shoe_01',
    name: 'Nike Air Jordan 1 Retro High OG Chicago',
    brand: 'Nike',
    category: 'Shoes',
    subcategory: 'Sneakers',
    description: 'The legendary sneaker that started it all. Premium genuine full-grain leather upper, encapsulated Nike Air cushioning, and the iconic Wings logo on the ankle collar.',
    price: 49999.0,
    oldPrice: 58999.0,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80',
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 2890,
    availableStock: 15,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#EF4444', '#0F172A'],
    sizes: ['40', '41', '42', '43', '44'],
    tags: ['nike', 'jordan 1', 'sneakers', 'streetwear', 'retro', 'shoes'],
    specifications: {
      'Upper': 'Full-Grain Natural Leather',
      'Sole': 'Solid Rubber with Pivot Circle',
      'Cushioning': 'Air-Sole unit in heel',
      'Authenticity': '100% Original Verified Stock',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days. Double boxed packaging.',
    sellerName: 'Kicks Vault Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_shoe_02',
    name: 'Adidas Ultraboost Light Running Shoes',
    brand: 'Adidas',
    category: 'Shoes',
    subcategory: 'Running Shoes',
    description: 'Experience epic energy return with the lightest Ultraboost ever made. 30% lighter Light BOOST material paired with Linear Energy Push system for explosive strides.',
    price: 38999.0,
    oldPrice: 44999.0,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
    rating: 4.8,
    reviewCount: 1670,
    availableStock: 30,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#F8FAFC'],
    sizes: ['41', '42', '43', '44', '45'],
    tags: ['adidas', 'ultraboost', 'running shoes', 'boost', 'fitness', 'sneakers'],
    specifications: {
      'Midsole': 'Light BOOST cushioning',
      'Outsole': 'Continental Better Rubber outsole',
      'Upper': 'PRIMEKNIT+ breathable textile',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Adidas Official Partner PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_shoe_03',
    name: 'Bata Heritage Handmade Leather Peshawari Chappal (Norzi)',
    brand: 'Bata',
    category: 'Shoes',
    subcategory: 'Loafers',
    description: 'Traditional craftsmanship meets modern durability. Handcrafted from top-grain cowhide leather with tyre-sole grip and adjustable side buckle for effortless eastern styling.',
    price: 5499.0,
    oldPrice: 6999.0,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
    rating: 4.8,
    reviewCount: 1420,
    availableStock: 80,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['40', '41', '42', '43', '44'],
    tags: ['peshawari chappal', 'bata', 'leather', 'norzi', 'eastern footwear', 'eid'],
    specifications: {
      'Upper': '100% Genuine Full-Grain Cow Leather',
      'Sole': 'Heavy-duty vulcanized rubber tyre sole',
      'Stitching': 'Dual nylon waxed thread hand-stitch',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Bata Pakistan Official',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_shoe_04',
    name: 'Servis Cheetah High-Traction Court Sneakers',
    brand: 'Servis',
    category: 'Shoes',
    subcategory: 'Sneakers',
    description: 'Pakistan’s most iconic sports sneakers. Lightweight canvas construction with reinforced rubber toe cap and gum-grip waffle outsole for courts, cricket, and casual wear.',
    price: 2499.0,
    oldPrice: 2999.0,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80',
    rating: 4.6,
    reviewCount: 3100,
    availableStock: 150,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#FFFFFF', '#0F172A'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    tags: ['cheetah', 'servis', 'sneakers', 'retro', 'pakistani classic', 'sports'],
    specifications: {
      'Upper': 'Heavy-duty 12oz Duck Canvas',
      'Sole': 'Natural Vulcanized Gum Rubber',
      'Insole': 'Cushioned EVA foam footbed',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Servis Official Store',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_shoe_05',
    name: 'Hush Puppies Oxford Formal Full-Grain Leather Shoes',
    brand: 'Hush Puppies',
    category: 'Shoes',
    subcategory: 'Formal Shoes',
    description: 'Classic cap-toe Oxford shoe engineered with ZeroG lightweight technology and Bounce comfort footbed that absorbs shocks and cushions every step.',
    price: 16999.0,
    oldPrice: 19999.0,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80',
    rating: 4.8,
    reviewCount: 580,
    availableStock: 25,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['40', '41', '42', '43', '44'],
    tags: ['oxford', 'hush puppies', 'formal shoes', 'leather', 'office', 'wedding'],
    specifications: {
      'Upper': 'Polished Full-Grain Calfskin Leather',
      'Insole': 'Bounce Pod Cushioning System',
      'Construction': 'Goodyear Welted Construction',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Hush Puppies Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_shoe_06',
    name: 'Nike Air Force 1 07 Low All-White Sneakers',
    brand: 'Nike',
    category: 'Shoes',
    subcategory: 'Sneakers',
    description: 'The radiance lives on in the Nike Air Force 1 07, the b-ball icon that puts a fresh spin on crisp leather, stitched overlays, and the perfect amount of flash.',
    price: 34999.0,
    oldPrice: 39999.0,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    rating: 4.9,
    reviewCount: 3410,
    availableStock: 40,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#FFFFFF'],
    sizes: ['40', '41', '42', '43', '44'],
    tags: ['nike', 'air force 1', 'white sneakers', 'classic', 'streetwear'],
    specifications: {
      'Upper': 'Crisp, easy-to-clean leather',
      'Midsole': 'Foam midsole with encapsulated Air-Sole unit',
      'Perforations': 'Toe box airflow perforations',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Sneaker Head PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_shoe_07',
    name: 'New Balance 574 Core Classic Sneakers (Grey)',
    brand: 'New Balance',
    category: 'Shoes',
    subcategory: 'Sneakers',
    description: 'The most New Balance shoe ever. Built to be a reliable shoe that could do a lot of different things well, with ENCAP midsole cushioning and suede/mesh upper.',
    price: 29999.0,
    oldPrice: 34999.0,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80',
    rating: 4.8,
    reviewCount: 920,
    availableStock: 32,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#64748B', '#0F172A'],
    sizes: ['41', '42', '43', '44'],
    tags: ['new balance', 'nb 574', 'grey sneakers', 'suede', 'casual shoes'],
    specifications: {
      'Cushioning': 'ENCAP midsole foam with durable polyurethane rim',
      'Upper': 'Suede leather and lightweight mesh',
      'Outsole': 'Carbon rubber lugged tread',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'New Balance Retail PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_shoe_08',
    name: 'Clarks Tilden Cap Leather Derby Dress Shoes',
    brand: 'Clarks',
    category: 'Shoes',
    subcategory: 'Formal Shoes',
    description: 'Rich, glossy leather upper with discrete elastic stretch gore panels for effortless on and off. Ortholite footbed wicks away moisture and softens impacts.',
    price: 19999.0,
    oldPrice: 23999.0,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80',
    rating: 4.7,
    reviewCount: 460,
    availableStock: 20,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['41', '42', '43', '44'],
    tags: ['clarks', 'derby', 'dress shoes', 'leather', 'formal footwear'],
    specifications: {
      'Upper': 'Smooth Natural Leather',
      'Insole': 'Cushion Soft with Ortholite Tech',
      'Sole': 'Durable lightweight TPR sole',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Footwear Lounge Lahore',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_shoe_09',
    name: 'Crocs Classic Clog Slip-On Sandal (Black)',
    brand: 'Crocs',
    category: 'Shoes',
    subcategory: 'Loafers',
    description: 'Lightweight, water-friendly Croslite foam construction with ventilation ports that shed water and debris. Pivoting heel strap gives a secure, personalized fit.',
    price: 7999.0,
    oldPrice: 9499.0,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800&q=80',
    rating: 4.7,
    reviewCount: 1850,
    availableStock: 95,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#F8FAFC', '#10B981'],
    sizes: ['M7/W9 (40)', 'M8/W10 (41)', 'M9/W11 (42)', 'M10/W12 (43)'],
    tags: ['crocs', 'clogs', 'sandals', 'croslite', 'casual slip on'],
    specifications: {
      'Material': 'Iconic Croslite closed-cell resin',
      'Cleaning': 'Easy to clean and quick to dry with soap & water',
      'Weight': 'Under 200g per shoe',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Crocs Pakistan Partner',
    sellerRating: 4.8,
  ),

  // ==================== 5. WATCHES (8 PRODUCTS) ====================
  const Product(
    id: 'prod_wat_01',
    name: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium',
    brand: 'Apple',
    category: 'Watches',
    subcategory: 'Smart Watches',
    description: 'The most rugged and capable Apple Watch. 49mm corrosion-resistant aerospace titanium case, 3000-nit display, precision dual-frequency GPS, and up to 72 hours of battery life.',
    price: 249999.0,
    oldPrice: 279999.0,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 1180,
    availableStock: 14,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78716C', '#EA580C'],
    sizes: ['49mm Case'],
    tags: ['apple watch', 'ultra 2', 'smartwatch', 'titanium', 'fitness', 'gps'],
    specifications: {
      'Case': '49mm Natural Aerospace Titanium',
      'Display': 'Always-On Retina OLED 3000 nits',
      'Water Resistance': '100m Water-resistant & 40m recreational dive',
      'Sensor': 'Blood Oxygen, ECG, Depth Gauge & Water Temp',
      'Warranty': '1 Year Apple Official Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2 business days. Insured delivery.',
    sellerName: 'Mercantile Official Apple Partner',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_wat_02',
    name: 'Samsung Galaxy Watch 6 Classic 47mm LTE (Black)',
    brand: 'Samsung',
    category: 'Watches',
    subcategory: 'Smart Watches',
    description: 'Timeless styling featuring the signature physical rotating bezel. Advanced sleep coaching, Body Composition (BIA) sensor, and comprehensive heart health monitoring.',
    price: 84999.0,
    oldPrice: 94999.0,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    rating: 4.8,
    reviewCount: 740,
    availableStock: 26,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#94A3B8'],
    sizes: ['47mm'],
    tags: ['samsung', 'galaxy watch 6', 'rotating bezel', 'smartwatch', 'lte'],
    specifications: {
      'Bezel': 'Physical Rotating Stainless Steel Bezel',
      'Glass': 'Sapphire Crystal Screen',
      'Battery': '425 mAh with Fast Wireless Charging',
      'OS': 'Wear OS powered by Samsung',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Samsung Official Flagship Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_wat_03',
    name: 'Tissot PRX Powermatic 80 Automatic (Blue Dial 40mm)',
    brand: 'Tissot',
    category: 'Watches',
    subcategory: 'Luxury Watches',
    description: 'Swiss-made luxury with 1970s integrated bracelet aesthetic. Features the Powermatic 80 caliber movement offering an 80-hour power reserve and Nivachron anti-magnetic balance spring.',
    price: 198999.0,
    oldPrice: 224999.0,
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
    rating: 4.9,
    reviewCount: 520,
    availableStock: 8,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#1E3A8A', '#0F172A'],
    sizes: ['40mm'],
    tags: ['tissot', 'prx', 'swiss watch', 'automatic', 'luxury watch', 'powermatic 80'],
    specifications: {
      'Movement': 'Swiss Automatic Powermatic 80.111',
      'Power Reserve': '80 Hours',
      'Case': '316L Stainless Steel with Exhibition Caseback',
      'Crystal': 'Scratch-resistant Sapphire with AR coating',
      'Warranty': '2 Years International Tissot Warranty',
    },
    deliveryInfo: 'Insured security courier delivery in 2 business days.',
    sellerName: 'Lifestyle Collection Pakistan',
    sellerRating: 5.0,
  ),
  const Product(
    id: 'prod_wat_04',
    name: 'Casio G-Shock GA-2100-1A1 "CasiOak" All-Black',
    brand: 'Casio',
    category: 'Watches',
    subcategory: 'Chronographs',
    description: 'Octagonal carbon core guard structure making it the slimmest G-Shock ever produced. Shock-resistant, 200m water-resistant with dual analog-digital illuminated display.',
    price: 31999.0,
    oldPrice: 36999.0,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80',
    rating: 4.8,
    reviewCount: 2150,
    availableStock: 50,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['45.4mm'],
    tags: ['g shock', 'casio', 'casioak', 'military watch', 'rugged', 'waterproof'],
    specifications: {
      'Structure': 'Carbon Core Guard Tough Resin',
      'Water Resistance': '200 Meters (20 Bar)',
      'Illumination': 'Super Illuminator Double LED light',
      'Battery Life': '3 Years on SR726W',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Casio Official Center PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_wat_05',
    name: 'Seiko 5 Sports Automatic SRPD55K1 Diver Watch',
    brand: 'Seiko',
    category: 'Watches',
    subcategory: 'Luxury Watches',
    description: 'Iconic dive-style automatic sports watch featuring Seiko Caliber 4R36 with manual winding and hacking seconds. Uni-directional rotating bezel and LumiBrite hands.',
    price: 74999.0,
    oldPrice: 84999.0,
    image: 'https://images.unsplash.com/photo-1547996160-71dfa63582d8?w=800&q=80',
    rating: 4.8,
    reviewCount: 880,
    availableStock: 18,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['42.5mm'],
    tags: ['seiko', 'seiko 5', 'automatic', 'dive watch', 'mechanical watch'],
    specifications: {
      'Caliber': 'Seiko 4R36 Automatic (24 Jewels)',
      'Power Reserve': 'Approx. 41 hours',
      'Water Resistance': '100 Meters with Screw-down case back',
      'Warranty': '1 Year Official Seiko Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Nizam Watch House',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_wat_06',
    name: 'Amazfit GTR 4 Smart Watch with Dual-Band GPS',
    brand: 'Amazfit',
    category: 'Watches',
    subcategory: 'Smart Watches',
    description: 'Ultra-long 14-day battery life, 1.43-inch HD AMOLED display, circular polarized GPS antenna, and 150+ sports modes with automatic strength exercise recognition.',
    price: 44999.0,
    oldPrice: 49999.0,
    image: 'https://images.unsplash.com/photo-1579586337278-3ffa51717f91?w=800&q=80',
    rating: 4.7,
    reviewCount: 610,
    availableStock: 35,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['46mm'],
    tags: ['amazfit', 'smartwatch', 'fitness watch', 'amoled', 'gps'],
    specifications: {
      'Screen': '1.43" HD AMOLED 466x466',
      'Battery': '14 Days typical usage',
      'GPS': 'Dual-band & 6 Satellite Positioning Systems',
      'Bluetooth': 'Phone calls & music storage on watch',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Amazfit Official PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_wat_07',
    name: 'Fossil Grant Chronograph Blue Dial Leather Watch',
    brand: 'Fossil',
    category: 'Watches',
    subcategory: 'Chronographs',
    description: 'Vintage-inspired dress chronograph with deep blue sunray dial and Roman numeral hour markers. Finished with a genuine luggage-brown saddle leather strap.',
    price: 36999.0,
    oldPrice: 42999.0,
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&q=80',
    rating: 4.7,
    reviewCount: 790,
    availableStock: 25,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#1E3A8A', '#78350F'],
    sizes: ['44mm'],
    tags: ['fossil', 'chronograph', 'leather watch', 'dress watch', 'grant'],
    specifications: {
      'Case': 'Stainless Steel 44mm Case',
      'Strap': '22mm Interchangeable Genuine Leather',
      'Movement': 'Quartz Chronograph with Stop Watch sub-dials',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Time Center Pakistan',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_wat_08',
    name: 'Citizen Eco-Drive Promaster Nighthawk Pilot Watch',
    brand: 'Citizen',
    category: 'Watches',
    subcategory: 'Chronographs',
    description: 'Powered by light — any light. Never needs a battery change. Features dual time GMT function, pilot’s slide rule inner bezel, and anti-reflective mineral crystal.',
    price: 89999.0,
    oldPrice: 99999.0,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    rating: 4.8,
    reviewCount: 370,
    availableStock: 12,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['42mm'],
    tags: ['citizen', 'eco drive', 'solar watch', 'pilot watch', 'gmt'],
    specifications: {
      'Solar Tech': 'Citizen Eco-Drive B877 movement',
      'Water Resistance': '200M (660 feet)',
      'Bezel': 'Pilot Slide Rule Dial Ring',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Citizen Authorized Dealer',
    sellerRating: 4.8,
  ),

  // ==================== 6. BAGS & ACCESSORIES (9 PRODUCTS) ====================
  const Product(
    id: 'prod_bag_01',
    name: 'Jawaani Handcrafted Full-Grain Cow Leather Laptop Messenger',
    brand: 'Jawaani Leather',
    category: 'Bags & Accessories',
    subcategory: 'Bags',
    description: 'Expertly handcrafted in Sialkot from thick, vegetable-tanned pull-up leather that develops a magnificent vintage patina over time. Fits up to a 16-inch laptop with padded velvet lining.',
    price: 18499.0,
    oldPrice: 22999.0,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
      'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 420,
    availableStock: 25,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78350F', '#0F172A'],
    sizes: ['16-inch Laptop Size'],
    tags: ['leather bag', 'laptop bag', 'messenger', 'handcrafted', 'sialkot leather', 'executive'],
    specifications: {
      'Material': '100% Genuine Full-Grain Vegetable-Tanned Cow Leather',
      'Hardware': 'Antique Solid Brass Buckles & YKK Zippers',
      'Laptop Compartment': 'High-density foam fits up to 16" MacBook Pro',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Jawaani Leather Works',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_bag_02',
    name: 'Markhor RFID-Blocking Minimalist Leather Bi-Fold Wallet',
    brand: 'Markhor',
    category: 'Bags & Accessories',
    subcategory: 'Wallets',
    description: 'Slimline bi-fold wallet engineered with certified RFID-blocking inner lining to protect cards against digital theft. Holds 10+ cards, currency bills, and micro SIM.',
    price: 3499.0,
    oldPrice: 4499.0,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    rating: 4.8,
    reviewCount: 1680,
    availableStock: 120,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78350F', '#0F172A'],
    sizes: [],
    tags: ['wallet', 'leather wallet', 'rfid blocking', 'markhor', 'men accessories'],
    specifications: {
      'Material': 'Top-Grain Waxed Crazy Horse Leather',
      'Protection': '13.56 MHz RFID Shielding',
      'Dimensions': '11 cm x 8.5 cm x 1.2 cm',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Markhor Crafts Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_bag_03',
    name: 'Ray-Ban Classic Aviator Polarized Sunglasses (Gold/G-15)',
    brand: 'Ray-Ban',
    category: 'Bags & Accessories',
    subcategory: 'Sunglasses',
    description: 'Originally created for U.S. Aviators in 1937. Iconic metal frame with crystal green G-15 polarized lenses that eliminate 99% of reflected glares.',
    price: 32999.0,
    oldPrice: 38999.0,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
    rating: 4.9,
    reviewCount: 950,
    availableStock: 30,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#D97706', '#0F172A'],
    sizes: ['58mm (Standard)', '62mm (Large)'],
    tags: ['ray ban', 'sunglasses', 'aviator', 'polarized', 'eyewear'],
    specifications: {
      'Frame': 'Polished Gold Monel Metal Alloy',
      'Lens': 'G-15 Green Polarized Mineral Glass',
      'UV Protection': '100% UV400 Protection',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Optics Elite PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_bag_04',
    name: 'TravelPro Crew 20-inch Expandable Hard-Shell Cabin Luggage',
    brand: 'TravelPro',
    category: 'Bags & Accessories',
    subcategory: 'Travel Gear',
    description: 'Ultra-lightweight 100% polycarbonate shell with scratch-resistant metallic texture, TSA-approved recessed combination lock, and 360-degree dual spinner wheels.',
    price: 24999.0,
    oldPrice: 29999.0,
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&q=80',
    rating: 4.8,
    reviewCount: 540,
    availableStock: 20,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#0D9488', '#E2E8F0'],
    sizes: ['20-inch Cabin Carry-on'],
    tags: ['luggage', 'suitcase', 'travelpro', 'trolley', 'cabin bag', 'travel'],
    specifications: {
      'Shell': 'Bayer 100% Makrolon Polycarbonate',
      'Lock': 'Built-in TSA Keyless Lock',
      'Capacity': '42 Liters (Expandable +5L)',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Travel Luggage Hub',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_bag_05',
    name: 'Hub Leather Women’s Structured Shoulder Tote Bag',
    brand: 'Hub Leather',
    category: 'Bags & Accessories',
    subcategory: 'Bags',
    description: 'Refined Italian grain cow leather tote featuring gold-toned zipper hardware, dual comfortable shoulder straps, and a structured base with protective metal feet.',
    price: 16990.0,
    oldPrice: 20990.0,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80',
    rating: 4.8,
    reviewCount: 480,
    availableStock: 25,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#78350F', '#0F172A', '#E11D48'],
    sizes: ['Medium Tote'],
    tags: ['hub leather', 'handbag', 'tote bag', 'women bag', 'genuine leather'],
    specifications: {
      'Leather': 'Embossed Pebble Grain Cowhide',
      'Compartments': 'Main zip pocket + 2 slip phone slots',
      'Lining': 'Stain-resistant Satin Jacquard',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Hub Leather Flagship',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_bag_06',
    name: 'Osprey Daylite Plus Commuter Everyday Backpack 20L',
    brand: 'Osprey',
    category: 'Bags & Accessories',
    subcategory: 'Bags',
    description: 'Comfortable mesh-covered die-cut foam backpanel providing ventilation and support. Padded interior sleeve fits 15" laptop or 2L hydration reservoir.',
    price: 17499.0,
    oldPrice: 19999.0,
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800&q=80',
    rating: 4.8,
    reviewCount: 690,
    availableStock: 35,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#1E3A8A'],
    sizes: ['20 Liters'],
    tags: ['osprey', 'backpack', 'laptop backpack', 'travel', 'daylite'],
    specifications: {
      'Volume': '20 Liters',
      'Fabric': '300D Recycled PET Packcloth with PFC-free DWR',
      'Weight': '585 Grams',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Outdoor Gear PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_bag_07',
    name: 'Tom Ford Snowdon Classic Acetate Sunglasses',
    brand: 'Tom Ford',
    category: 'Bags & Accessories',
    subcategory: 'Sunglasses',
    description: 'Iconic chunky bold square acetate silhouette with the signature metallic "T" hinge temple insert. 100% UVA/UVB blue-block polarized optics.',
    price: 49999.0,
    oldPrice: 59999.0,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&q=80',
    rating: 4.9,
    reviewCount: 240,
    availableStock: 10,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A', '#78350F'],
    sizes: ['50mm'],
    tags: ['tom ford', 'luxury sunglasses', 'eyewear', 'acetate', 'fashion'],
    specifications: {
      'Material': 'Premium Italian Mazzucchelli Acetate',
      'Hinge': 'Signature Gold-Plated "T" Logo Temple',
      'Includes': 'Velvet Hard Case, Authenticity Card & Cloth',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Luxury Optical Studio',
    sellerRating: 5.0,
  ),
  const Product(
    id: 'prod_bag_08',
    name: 'Bellroy Classic Water-Resistant Pouch Plus for Tech',
    brand: 'Bellroy',
    category: 'Bags & Accessories',
    subcategory: 'Wallets',
    description: 'Keep chargers, power banks, cables, SSDs, and styluses neatly organized in one grab-and-go case with origami-style magnetic fold-out pockets.',
    price: 9999.0,
    oldPrice: 11999.0,
    image: 'https://images.unsplash.com/photo-1582142407894-ec85a1260a46?w=800&q=80',
    rating: 4.8,
    reviewCount: 410,
    availableStock: 45,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#64748B'],
    sizes: ['One Size'],
    tags: ['bellroy', 'tech pouch', 'cable organizer', 'travel kit', 'accessories'],
    specifications: {
      'Material': 'Water-resistant woven fabric from recycled plastic bottles',
      'Opening': 'Full clamshell zip opening',
      'Warranty': '3 Years Bellroy Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Everyday Carry Pakistan',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_bag_09',
    name: 'Delsey Paris Chatelet Air 2.0 Duffel Overnight Weekender',
    brand: 'Delsey',
    category: 'Bags & Accessories',
    subcategory: 'Travel Gear',
    description: 'Chic Parisian weekend travel bag crafted from durable chevron-patterned twill fabric with vegan leather trims. Rear smart sleeve slides easily over trolley handles.',
    price: 28999.0,
    oldPrice: 34999.0,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
    rating: 4.8,
    reviewCount: 310,
    availableStock: 18,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#F5F5F4', '#0F172A'],
    sizes: ['45 Liters'],
    tags: ['delsey', 'duffel bag', 'weekender', 'luggage', 'travel'],
    specifications: {
      'Dimensions': '30 x 53 x 28 cm',
      'Material': 'Recycled Polycarbonate Twill with Eco-leather',
      'Warranty': '5 Years Global Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Delsey Paris Boutique PK',
    sellerRating: 4.9,
  ),

  // ==================== 7. HOME & LIVING (9 PRODUCTS) ====================
  const Product(
    id: 'prod_home_01',
    name: 'Philips Series 2200 Fully Automatic Espresso Machine',
    brand: 'Philips',
    category: 'Home & Living',
    subcategory: 'Kitchen',
    description: 'Delicious fresh coffee and cappuccino from whole beans at the touch of a button. Classic milk frother dispenses silky smooth froth for rich barista-grade beverages at home.',
    price: 139999.0,
    oldPrice: 159999.0,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 620,
    availableStock: 16,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: [],
    tags: ['philips', 'coffee machine', 'espresso', 'kitchen', 'home appliances'],
    specifications: {
      'Grinder': '100% Pure Ceramic Grinder with 12 steps',
      'Water Filter': 'AquaClean eliminates descaling for up to 5,000 cups',
      'Pump Pressure': '15 Bar Italian Pressure Pump',
      'Warranty': '2 Years Official Philips Pakistan Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days. Heavy item insured shipping.',
    sellerName: 'Philips Domestic Appliances PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_home_02',
    name: 'Xiaomi Smart Air Purifier 4 Pro with Laser Particle Sensor',
    brand: 'Xiaomi',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    description: 'Filters 99.97% of 0.3μm particles, smog, and pet dander with 500m³/h Clean Air Delivery Rate (CADR). Low-noise night mode and Mi Home App smart scheduling.',
    price: 54999.0,
    oldPrice: 62999.0,
    image: 'https://images.unsplash.com/photo-1585862705646-7c9eb145f7c3?w=800&q=80',
    rating: 4.8,
    reviewCount: 950,
    availableStock: 28,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#F8FAFC'],
    sizes: [],
    tags: ['air purifier', 'xiaomi', 'smog', 'home appliances', 'smart home'],
    specifications: {
      'Coverage Area': 'Up to 60 m² (Room volume)',
      'CADR': '500m³/h (Particle)',
      'Filter Life': 'Up to 12 months with high-efficiency 3-in-1 layer',
      'Smart Assistant': 'Google Assistant & Alexa compatible',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Xiaomi Smart Home Flagship',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_03',
    name: 'Anex Deluxe 7-in-1 Food Processor & Dough Kneader',
    brand: 'Anex',
    category: 'Home & Living',
    subcategory: 'Kitchen',
    description: 'Workhorse Pakistani kitchen powerhouse. Includes blender jug, dry spice grinder, chopper, citrus juicer, stainless steel slicing discs, and atta dough kneader hook.',
    price: 19499.0,
    oldPrice: 22999.0,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80',
    rating: 4.7,
    reviewCount: 1840,
    availableStock: 65,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#E2E8F0'],
    sizes: [],
    tags: ['anex', 'food processor', 'kitchen', 'dough kneader', 'appliances', 'blender'],
    specifications: {
      'Motor': '1000W Pure Copper Heavy Duty Motor',
      'Bowl Capacity': '2.0 Liters Impact Resistant Bowl',
      'Warranty': '2 Years Official Anex Pakistan Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Anex Official Store',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_04',
    name: 'Philips Airfryer XXL Smart Sensing 7.2L 2000W',
    brand: 'Philips',
    category: 'Home & Living',
    subcategory: 'Kitchen',
    description: 'Fry with up to 90% less oil thanks to Rapid Air technology. Smart Sensing technology automatically adjusts time and temperature for perfectly crispy Pakistani samosas, fish, and chicken roast.',
    price: 49999.0,
    oldPrice: 58999.0,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80',
    rating: 4.9,
    reviewCount: 1250,
    availableStock: 30,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: [],
    tags: ['airfryer', 'philips', 'healthy cooking', 'kitchen', 'crispy'],
    specifications: {
      'Capacity': '7.2 Liters / 1.4kg Fries Capacity',
      'Power': '2000W High Speed Rapid Air',
      'Coating': 'QuickClean non-stick basket dishwasher safe',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Philips Kitchen Store',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_home_05',
    name: 'Himalayan Hand-Carved Natural Pink Salt Crystal Lamp with Dimmer',
    brand: 'Khewra Heritage',
    category: 'Home & Living',
    subcategory: 'Lighting',
    description: 'Authentic 100% natural pink salt mined from Khewra Salt Mines. Mounted on a polished neem wooden base with certified UL dimmer switch cord and warm amber bulb.',
    price: 2499.0,
    oldPrice: 3299.0,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    rating: 4.8,
    reviewCount: 2190,
    availableStock: 140,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#F97316'],
    sizes: ['3-4 kg Standard'],
    tags: ['salt lamp', 'himalayan salt', 'khewra', 'ambient lighting', 'home decor'],
    specifications: {
      'Weight': '3.0 - 4.5 Kilograms',
      'Base': 'Hand-turned Neem Wood Base',
      'Cord': '1.5m Safety Dimmable Cord & 15W Bulb included',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Khewra Artisan Crafts',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_06',
    name: 'Nespresso Vertuo Pop Automatic Capsule Coffee Pod Machine',
    brand: 'Nespresso',
    category: 'Home & Living',
    subcategory: 'Kitchen',
    description: 'Compact colorful coffee pod maker brewing four cup sizes from Espresso (40ml) to Mug (230ml) using patented Centrifusion brewing technology rotating at 4,000 RPM.',
    price: 44999.0,
    oldPrice: 49999.0,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    rating: 4.7,
    reviewCount: 380,
    availableStock: 20,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#EF4444', '#0F172A', '#EAB308'],
    sizes: [],
    tags: ['nespresso', 'coffee pods', 'espresso', 'kitchen', 'vertuo'],
    specifications: {
      'Water Tank': '600 ml removable reservoir',
      'Heat-up Time': 'Fast 30 seconds',
      'Connectivity': 'Bluetooth Smart & Wi-Fi',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days.',
    sellerName: 'Nespresso Boutique PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_07',
    name: 'Black+Decker 2400W Ceramic Steam Iron with Anti-Calc',
    brand: 'Black+Decker',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    description: 'Smooth-gliding ceramic soleplate delivering 140g/min burst of steam to remove tough creases from heavy cotton kurtas and linen suits effortlessly.',
    price: 11499.0,
    oldPrice: 13999.0,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&q=80',
    rating: 4.7,
    reviewCount: 810,
    availableStock: 50,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#3B82F6'],
    sizes: [],
    tags: ['iron', 'steam iron', 'black and decker', 'home care', 'appliances'],
    specifications: {
      'Power': '2400 Watts Rapid Heating',
      'Soleplate': 'Multi-hole Ceramic Non-Stick',
      'Anti-Drip': 'Yes with self-clean anti-calc system',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Black+Decker Official Store',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_08',
    name: 'Prestige 10-Piece Granite Non-Stick Cookware Set',
    brand: 'Prestige',
    category: 'Home & Living',
    subcategory: 'Kitchen',
    description: 'Multi-layer scratch-resistant granite non-stick coating suitable for all stovetops including gas and induction. Includes karahi, saucepans, tawa, and tempered glass lids.',
    price: 26999.0,
    oldPrice: 32999.0,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80',
    rating: 4.8,
    reviewCount: 670,
    availableStock: 22,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#334155'],
    sizes: ['10-Piece Set'],
    tags: ['cookware', 'non stick', 'pots and pans', 'kitchen', 'granite set', 'karahi'],
    specifications: {
      'Coating': 'PFOA-free German Greblon 4-Layer Granite Coating',
      'Thickness': '4.5mm Heavy Die-Cast Aluminum Base',
      'Handles': 'Stay-cool soft touch bakelite handles',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Prestige Cookware PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_home_09',
    name: 'Minimalist Nordic Dimmable LED Floor Standing Corner Lamp',
    brand: 'Luminaire',
    category: 'Home & Living',
    subcategory: 'Lighting',
    description: 'Ultra-slim corner design with 16 million RGB colors and warm white illumination. Controllable via RF touch remote and smartphone music-sync app.',
    price: 8999.0,
    oldPrice: 11499.0,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    rating: 4.6,
    reviewCount: 540,
    availableStock: 45,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['140cm Height'],
    tags: ['floor lamp', 'corner lamp', 'rgb', 'lighting', 'home decor', 'modern'],
    specifications: {
      'Height': '140 cm / 55 inches',
      'Brightness': 'Dimmable 10% to 100%',
      'Modes': '300+ Dynamic lighting effects & static warm glow',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Modern Living Lighting',
    sellerRating: 4.7,
  ),

  // ==================== 8. BEAUTY & CARE (9 PRODUCTS) ====================
  const Product(
    id: 'prod_beau_01',
    name: "Bleu de Chanel Eau de Parfum for Men 100ml",
    brand: 'Chanel',
    category: 'Beauty & Care',
    subcategory: 'Fragrances',
    description: 'An aromatic-woody fragrance with amber and musky notes. A tribute to masculine freedom, expressed in an enigmatic blue bottle. 100% original imported tester guaranteed.',
    price: 54999.0,
    oldPrice: 62999.0,
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
      'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 1650,
    availableStock: 20,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['100ml EDP'],
    tags: ['perfume', 'chanel', 'fragrance', 'bleu de chanel', 'men perfume', 'luxury'],
    specifications: {
      'Volume': '100 ml / 3.4 fl. oz.',
      'Concentration': 'Eau de Parfum (EDP)',
      'Top Notes': 'Grapefruit, Lemon, Mint, Pink Pepper',
      'Heart Notes': 'Ginger, Nutmeg, Jasmine, Iso E Super',
      'Base Notes': 'Incense, Vetiver, Cedar, Sandalwood, Patchouli',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days. Original sealed box.',
    sellerName: 'Scentsation Official Partner',
    sellerRating: 5.0,
  ),
  const Product(
    id: 'prod_beau_02',
    name: 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin 473ml',
    brand: 'CeraVe',
    category: 'Beauty & Care',
    subcategory: 'Skincare',
    description: 'Developed with dermatologists. Non-foaming lotion that cleanses, hydrates, and helps restore the protective skin barrier with 3 essential ceramides and hyaluronic acid.',
    price: 5499.0,
    oldPrice: 6499.0,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
    rating: 4.9,
    reviewCount: 2890,
    availableStock: 80,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['473ml Large'],
    tags: ['cerave', 'cleanser', 'skincare', 'dermatologist', 'hydrating', 'face wash'],
    specifications: {
      'Volume': '473 ml / 16 oz',
      'Key Ingredients': 'Ceramides 1, 3, 6-II, Hyaluronic Acid',
      'Skin Type': 'Normal to Dry / Sensitive',
      'Formula': 'Fragrance-free, non-comedogenic',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'DermStore Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_beau_03',
    name: 'The Ordinary Niacinamide 10% + Zinc 1% High-Strength Serum 60ml',
    brand: 'The Ordinary',
    category: 'Beauty & Care',
    subcategory: 'Skincare',
    description: 'High-strength vitamin and mineral blemish formula. Niacinamide (Vitamin B3) reduces the appearance of skin blemishes, visibly brightens skin tone, and balances sebum production.',
    price: 4199.0,
    oldPrice: 4999.0,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
    rating: 4.8,
    reviewCount: 3240,
    availableStock: 95,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['60ml Supersize'],
    tags: ['the ordinary', 'serum', 'niacinamide', 'skincare', 'acne', 'blemishes'],
    specifications: {
      'Volume': '60 ml',
      'Key Actives': '10% Niacinamide + 1% Zinc PCA',
      'pH Level': '5.00 - 6.50',
      'Targets': 'Oiliness, enlarged pores, skin texture',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Beauty Glaze Official',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_beau_04',
    name: 'Dior Sauvage Eau de Parfum for Men 100ml',
    brand: 'Dior',
    category: 'Beauty & Care',
    subcategory: 'Fragrances',
    description: 'The powerful freshness of Sauvage exudes new sensual and mysterious facets. Calabrian bergamot, raw and noble, invigorates juicy spicy notes while vanilla absolute envelops.',
    price: 58999.0,
    oldPrice: 65999.0,
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
    rating: 4.9,
    reviewCount: 2100,
    availableStock: 15,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['100ml EDP'],
    tags: ['dior', 'sauvage', 'perfume', 'edp', 'luxury perfume', 'men fragrance'],
    specifications: {
      'Volume': '100 ml',
      'Notes': 'Reggio Bergamot, Papua New Guinean Vanilla, Amberwood',
      'Concentration': 'Eau de Parfum',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Scents Lounge Karachi',
    sellerRating: 5.0,
  ),
  const Product(
    id: 'prod_beau_05',
    name: 'Philips Series 7000 Wet & Dry Electric Beard Trimmer',
    brand: 'Philips',
    category: 'Beauty & Care',
    subcategory: 'Grooming',
    description: 'Self-sharpening stainless steel blades with BeardSense technology that scans beard density 125 times per second. 20 length settings from 0.5mm to 10mm.',
    price: 15999.0,
    oldPrice: 18999.0,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80',
    rating: 4.7,
    reviewCount: 880,
    availableStock: 40,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: [],
    tags: ['philips', 'trimmer', 'grooming', 'beard trimmer', 'shaver'],
    specifications: {
      'Run Time': 'Up to 90 minutes cordless use',
      'Charge Time': '1 hour full charge',
      'Precision': '0.5mm precision zoom dial',
      'Washable': '100% Fully washable underwater',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Philips Personal Care',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_beau_06',
    name: 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF50+',
    brand: 'La Roche-Posay',
    category: 'Beauty & Care',
    subcategory: 'Skincare',
    description: 'Ultimate broad-spectrum sun protection against ultra-long UVA rays. Ultra-fluid texture, invisible finish, non-greasy, non-sticky, and extremely resistant to water and sweat.',
    price: 6899.0,
    oldPrice: 7999.0,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80',
    rating: 4.9,
    reviewCount: 1720,
    availableStock: 60,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['50ml'],
    tags: ['sunscreen', 'la roche posay', 'spf50', 'anthelios', 'skincare'],
    specifications: {
      'Protection': 'SPF50+ / PPD 46 High Broad Spectrum',
      'Filter': 'Patented Mexoryl 400 UV Filter',
      'Sensitivity': 'Suitable for reactive, sun-allergic skin',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Pharmacy Direct PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_beau_07',
    name: 'Olaplex No. 3 Hair Perfector Repairing Treatment 100ml',
    brand: 'Olaplex',
    category: 'Beauty & Care',
    subcategory: 'Hair Care',
    description: 'A global bestseller at-home weekly treatment that reduces breakage and visibly strengthens hair, improving its look and feel. Patented bond-building technology relinks broken disulfide bonds.',
    price: 8999.0,
    oldPrice: 10499.0,
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80',
    rating: 4.8,
    reviewCount: 940,
    availableStock: 35,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['100ml'],
    tags: ['olaplex', 'hair care', 'hair perfector', 'damaged hair repair', 'hair treatment'],
    specifications: {
      'Hair Type': 'All hair types, especially color-treated or damaged',
      'Formula': 'Sulfate-Free, Paraben-Free, Vegan & Cruelty-Free',
      'Usage': 'Apply to damp hair from roots to ends for 10-30 min',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Salon Professional PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_beau_08',
    name: 'COSRX Advanced Snail 96 Mucin Power Essence 100ml',
    brand: 'COSRX',
    category: 'Beauty & Care',
    subcategory: 'Skincare',
    description: 'Enriched with 96.3% skin-boosting Snail Secretion Filtrate. Lightweight essence absorbs quickly into skin to impart a natural glow from inside while replenishing long-lasting hydration.',
    price: 5299.0,
    oldPrice: 6199.0,
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&q=80',
    rating: 4.9,
    reviewCount: 2480,
    availableStock: 70,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: true,
    isDeal: true,
    colors: [],
    sizes: ['100ml'],
    tags: ['cosrx', 'snail mucin', 'k beauty', 'skincare', 'essence', 'korean'],
    specifications: {
      'Key Active': '96.3% Snail Secretion Filtrate',
      'Texture': 'Elastic hydrating serum-essence',
      'Benefits': 'Soothes redness, repairs skin barrier, deep moisture',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'K-Beauty Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_beau_09',
    name: 'Lattafa Asad Eau de Parfum for Men 100ml',
    brand: 'Lattafa',
    category: 'Beauty & Care',
    subcategory: 'Fragrances',
    description: 'Viral Arabic vanilla-peppery fragrance sensation. Rich blend of black pepper, tobacco, pineapple, patchouli, amber, dry wood, and benzoin.',
    price: 7499.0,
    oldPrice: 8999.0,
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&q=80',
    rating: 4.8,
    reviewCount: 3100,
    availableStock: 90,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['100ml'],
    tags: ['lattafa', 'asad', 'arabic perfume', 'oud', 'vanilla', 'perfume'],
    specifications: {
      'Concentration': 'Eau de Parfum (EDP)',
      'Longevity': '8–12 Hours long-lasting projection',
      'Country of Origin': 'United Arab Emirates (Dubai)',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Arabian Oud Boutique',
    sellerRating: 4.8,
  ),

  // ==================== 9. SPORTS & FITNESS (8 PRODUCTS) ====================
  const Product(
    id: 'prod_sport_01',
    name: 'Bowflex SelectTech 552 Adjustable Dumbbells Pair',
    brand: 'Bowflex',
    category: 'Sports & Fitness',
    subcategory: 'Fitness Equipment',
    description: 'Rapid selection dial system adjusts weight from 5 to 52.5 lbs (2.5 to 24 kg) in small increments. Replaces 15 pairs of traditional bulky weights with quiet, durable molding.',
    price: 54999.0,
    oldPrice: 64999.0,
    image: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800&q=80',
    rating: 4.8,
    reviewCount: 880,
    availableStock: 18,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A', '#EF4444'],
    sizes: ['Pair (5-52.5 lbs)'],
    tags: ['dumbbells', 'bowflex', 'gym', 'workout', 'weights', 'fitness equipment'],
    specifications: {
      'Weight Range': '5 to 52.5 lbs per dumbbell (2.3 to 23.8 kg)',
      'Plates': 'Durable molding around metal plates for smooth lift-off',
      'Warranty': '2 Years Mechanical Warranty',
    },
    deliveryInfo: 'Estimated delivery: 2–4 business days. Heavy parcel shipping.',
    sellerName: 'Fitness Pro Pakistan',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_sport_02',
    name: 'Lululemon Align High-Rise 6mm Reversible Yoga Mat',
    brand: 'Lululemon',
    category: 'Sports & Fitness',
    subcategory: 'Yoga & Pilates',
    description: 'Natural rubber base with antimicrobial polyurethane top layer absorbs sweat and offers unmatched non-slip grip during hot yoga, pilates, and floor stretching workouts.',
    price: 18999.0,
    oldPrice: 22999.0,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
    rating: 4.9,
    reviewCount: 640,
    availableStock: 35,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#065F46', '#4C1D95', '#0F172A'],
    sizes: ['66cm x 180cm (6mm Thick)'],
    tags: ['lululemon', 'yoga mat', 'pilates', 'non slip', 'fitness', 'rubber mat'],
    specifications: {
      'Thickness': '6mm Ultra-Dense Joint Cushioning',
      'Material': 'Natural Rubber Base + Polyurethane Surface',
      'Antimicrobial': 'Treated with antimicrobial additive',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Active Lifestyle PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_sport_03',
    name: 'Hydro Flask 32oz Wide Mouth Vacuum Insulated Bottle',
    brand: 'Hydro Flask',
    category: 'Sports & Fitness',
    subcategory: 'Accessories',
    description: 'TempShield double-wall vacuum insulation keeps ice cold for up to 24 hours or steaming hot for up to 12 hours. Pure pro-grade 18/8 stainless steel prevents flavor transfer.',
    price: 9499.0,
    oldPrice: 11499.0,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
    rating: 4.8,
    reviewCount: 1420,
    availableStock: 80,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0284C7', '#0F172A', '#10B981'],
    sizes: ['32 oz (946 ml)'],
    tags: ['hydro flask', 'water bottle', 'insulated', 'stainless steel', 'gym bottle'],
    specifications: {
      'Capacity': '32 oz / 946 ml',
      'Insulation': 'TempShield Double-Wall Vacuum',
      'Finish': 'Color Last powder coat is dishwasher safe',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Hydro Flask Direct',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_sport_04',
    name: 'Gymshark Apex High-Speed Ball-Bearing Jump Rope',
    brand: 'Gymshark',
    category: 'Sports & Fitness',
    subcategory: 'Accessories',
    description: 'Engineered for double-unders and high-intensity cardio. Dual 360-degree precision steel ball bearings in knurled non-slip aluminum handles with kink-free PVC coated steel cable.',
    price: 3499.0,
    oldPrice: 4499.0,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    rating: 4.7,
    reviewCount: 780,
    availableStock: 110,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['3 Meter Adjustable Cable'],
    tags: ['jump rope', 'gymshark', 'crossfit', 'skipping rope', 'cardio', 'boxing'],
    specifications: {
      'Bearings': 'Dual 360° High-Velocity Steel Ball Bearings',
      'Handles': 'Aviation-grade Knurled Aluminum',
      'Cable': '3m PVC Coated 2.5mm Steel Cable (Custom Cut)',
    },
    deliveryInfo: 'Estimated delivery: 2 business days.',
    sellerName: 'Speed Athletics PK',
    sellerRating: 4.8,
  ),
  const Product(
    id: 'prod_sport_05',
    name: 'Under Armour Men HeatGear 2.0 Compression Leggings',
    brand: 'Under Armour',
    category: 'Sports & Fitness',
    subcategory: 'Activewear',
    description: 'Ultra-light HeatGear fabric delivers superior coverage without weighing you down. Strategic mesh panels provide added ventilation where you need it most.',
    price: 8499.0,
    oldPrice: 9999.0,
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    rating: 4.8,
    reviewCount: 520,
    availableStock: 45,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['under armour', 'compression', 'gym tights', 'heatgear', 'fitness apparel'],
    specifications: {
      'Fabric': '84% Polyester, 16% Elastane HeatGear',
      'Tech': '4-way stretch material moves better in every direction',
      'Pocket': 'Drop-in Strength Pocket on right side for phone',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Under Armour Authorized PK',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_sport_06',
    name: 'Optimum Nutrition Gold Standard 100% Whey Protein 5lbs',
    brand: 'Optimum Nutrition',
    category: 'Sports & Fitness',
    subcategory: 'Accessories',
    description: 'The world’s best-selling whey protein. 24g of high-quality protein per scoop primarily from Whey Protein Isolate (WPI), with 5.5g of naturally occurring BCAAs. Double Rich Chocolate flavor.',
    price: 24999.0,
    oldPrice: 28999.0,
    image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&q=80',
    rating: 4.9,
    reviewCount: 3820,
    availableStock: 50,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isDeal: true,
    colors: [],
    sizes: ['5 lbs (74 Servings)'],
    tags: ['protein', 'whey protein', 'optimum nutrition', 'supplements', 'bodybuilding', 'gym'],
    specifications: {
      'Protein Per Serving': '24 Grams Pure Whey Isolate & Concentrate',
      'Servings': '74 Servings per tub',
      'Authenticity': 'Original TruMade Scratch Code verification',
    },
    deliveryInfo: 'Estimated delivery: 1–2 business days in major cities.',
    sellerName: 'NutriSport Pakistan (Authorized Importer)',
    sellerRating: 4.9,
  ),
  const Product(
    id: 'prod_sport_07',
    name: 'IronGym Total Upper Body Pull-Up Doorway Trainer Bar',
    brand: 'IronGym',
    category: 'Sports & Fitness',
    subcategory: 'Fitness Equipment',
    description: 'Leverage design hooks securely into any standard residential doorway without drilling or screws. Supports wide, narrow, and neutral grip pull-ups, push-ups, and dips.',
    price: 4999.0,
    oldPrice: 6499.0,
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80',
    rating: 4.6,
    reviewCount: 910,
    availableStock: 60,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#0F172A'],
    sizes: [],
    tags: ['pull up bar', 'iron gym', 'doorway trainer', 'calisthenics', 'home gym'],
    specifications: {
      'Weight Capacity': 'Up to 136 kg (300 lbs)',
      'Door Width Fit': 'Fits 24" to 32" standard door frames',
      'Grips': 'High-density comfort foam padding',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Home Fitness Gears PK',
    sellerRating: 4.7,
  ),
  const Product(
    id: 'prod_sport_08',
    name: 'Everlast Pro Style Elite Training Boxing Gloves 12oz',
    brand: 'Everlast',
    category: 'Sports & Fitness',
    subcategory: 'Accessories',
    description: 'Engineered with Evershield wrist reinforcement to protect hands and wrists during heavy bag punching and sparring. Breathable Evercool mesh palm keeps hands dry.',
    price: 9999.0,
    oldPrice: 11999.0,
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80',
    rating: 4.8,
    reviewCount: 630,
    availableStock: 30,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: false,
    isDeal: true,
    colors: ['#EF4444', '#0F172A'],
    sizes: ['12 oz', '14 oz'],
    tags: ['boxing gloves', 'everlast', 'sparring', 'mma', 'punching bag', 'boxing'],
    specifications: {
      'Material': 'Durable synthetic poly-leather',
      'Protection': 'Multi-layered shock absorbing foam',
      'Closure': 'Full wraparound hook-and-loop strap',
    },
    deliveryInfo: 'Estimated delivery: 2–3 business days.',
    sellerName: 'Everlast Combat Sports PK',
    sellerRating: 4.8,
  ),
];
